name: omnisam1
channels:
  - https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/free/
  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgomp=15.2.0=he0feb66_16
  - liblzma=5.8.2=hb03c661_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.2=h0c1763c_0
  - libuuid=2.41.3=h5347b49_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.1=h35e630c_1
  - packaging=26.0=pyhcf101f3_0
  - pip=25.3=pyh8b19718_0
  - python=3.10.19=h3c07f61_3_cpython
  - readline=8.3=h853b02a_0
  - setuptools=80.10.2=pyh332efcf_0
  - tk=8.6.13=noxft_h366c992_103
  - wheel=0.46.3=pyhd8ed1ab_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
    - addict==2.4.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.12.1
    - appdirs==1.4.4
    - argon2-cffi==25.1.0
    - argon2-cffi-bindings==25.1.0
    - arrow==1.4.0
    - asttokens==3.0.1
    - async-lru==2.1.0
    - attrs==25.4.0
    - babel==2.17.0
    - beautifulsoup4==4.14.3
    - bleach==6.3.0
    - certifi==2026.1.4
    - cffi==2.0.0
    - charset-normalizer==3.4.4
    - click==8.3.1
    - colorama==0.4.6
    - comm==0.2.3
    - contourpy==1.3.2
    - cycler==0.12.1
    - debugpy==1.8.19
    - decorator==5.2.1
    - defusedxml==0.7.1
    - docker-pycreds==0.4.0
    - eva-decord==0.6.1
    - exceptiongroup==1.3.1
    - executing==2.2.1
    - fastjsonschema==2.21.2
    - filelock==3.20.0
    - fonttools==4.61.1
    - fqdn==1.5.1
    - fsspec==2025.12.0
    - gitdb==4.0.12
    - gitpython==3.1.46
    - h11==0.16.0
    - hf-xet==1.2.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface-hub==1.3.4
    - hydra-core==1.3.2
    - icecream==2.1.10
    - idna==3.11
    - iopath==0.1.10
    - ipykernel==7.1.0
    - ipython==8.38.0
    - ipywidgets==8.1.8
    - isoduration==20.11.0
    - jedi==0.19.2
    - jinja2==3.1.6
    - json5==0.13.0
    - jsonpointer==3.0.0
    - jsonschema==4.26.0
    - jsonschema-specifications==2025.9.1
    - jupyter==1.1.1
    - jupyter-client==8.8.0
    - jupyter-console==6.6.3
    - jupyter-core==5.9.1
    - jupyter-events==0.12.0
    - jupyter-lsp==2.3.0
    - jupyter-server==2.17.0
    - jupyter-server-terminals==0.5.4
    - jupyterlab==4.5.3
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.28.0
    - jupyterlab-widgets==3.0.16
    - kiwisolver==1.4.9
    - lark==1.3.1
    - markdown-it-py==4.0.0
    - markupsafe==2.1.5
    - matplotlib==3.10.8
    - matplotlib-inline==0.2.1
    - mdurl==0.1.2
    - mistune==3.2.0
    - mmcv==2.1.0
    - mmengine==0.10.7
    - mpmath==1.3.0
    - nbclient==0.10.4
    - nbconvert==7.16.6
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - networkx==3.4.2
    - notebook==7.5.3
    - notebook-shim==0.2.4
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.9.86
    - nvidia-nvtx-cu12==12.1.105
    - omegaconf==2.3.0
    - opencv-python==4.9.0.80
    - overrides==7.7.0
    - pandocfilters==1.5.1
    - parso==0.8.5
    - pexpect==4.9.0
    - pillow==12.0.0
    - platformdirs==4.5.1
    - portalocker==3.2.0
    - prometheus-client==0.24.1
    - prompt-toolkit==3.0.52
    - protobuf==4.25.8
    - psutil==7.2.2
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pycparser==3.0
    - pygments==2.19.2
    - pyparsing==3.3.2
    - python-dateutil==2.9.0.post0
    - python-json-logger==4.0.0
    - pyyaml==6.0.3
    - pyzmq==27.1.0
    - referencing==0.37.0
    - requests==2.32.5
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rfc3987-syntax==1.1.0
    - rich==14.3.1
    - rpds-py==0.30.0
    - safetensors==0.7.0
    - sam-2==1.0
    - send2trash==2.1.0
    - sentry-sdk==2.51.0
    - setproctitle==1.3.7
    - shellingham==1.5.4
    - six==1.17.0
    - smmap==5.0.2
    - soupsieve==2.8.3
    - stack-data==0.6.3
    - sympy==1.13.1
    - termcolor==3.3.0
    - terminado==0.18.1
    - timm==1.0.24
    - tinycss2==1.4.0
    - tomli==2.4.0
    - torch==2.5.1+cu121
    - torchaudio==2.5.1+cu121
    - torchvision==0.20.1+cu121
    - tornado==6.5.4
    - tqdm==4.67.1
    - traitlets==5.14.3
    - triton==3.1.0
    - typer-slim==0.21.1
    - typing-extensions==4.15.0
    - tzdata==2025.3
    - uri-template==1.3.0
    - urllib3==2.6.3
    - wandb==0.16.6
    - wcwidth==0.5.0
    - webcolors==25.10.0
    - webencodings==0.5.1
    - websocket-client==1.9.0
    - widgetsnbextension==4.0.15
    - yapf==0.43.0
prefix: /data0/zhangyudong/.conda/envs/omnisam1
